### ISSUE TITLE
Bond force expects 3 particles in bond

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/alchemy#23]
[Looks like](https://github.com/choderalab/alchemy/blob/master/alchemy/alchemy.py#L761) the `AbsoluteAlchemicalFactory` tries to get 3 particles out of a `HarmonicBondForce` term. I can fix this unless someone else is itching to do it.

**Comment by jchodera** [comment]
Let me fix.

**Comment by pgrinaway** [comment]
ok

**Comment by jchodera** [comment]
Created a PR to fix.
