### ISSUE TITLE
Citeable releases

### ISSUE THREAD

**Issue by bas-rustenburg** [choderalab/alchemy#36]
Would it be possible to add doi links to alchemy releases using something like zenodo? 
https://zenodo.org/

I think it'll be important and useful in any papers that will depend on alchemy.

**Comment by jchodera** [comment]
Sure!

**Comment by jchodera** [comment]
Is there a way to automate this?

**Comment by bas-rustenburg** [comment]
Yes. Log in and you can do it here: https://zenodo.org/account/settings/github/

**Comment by jchodera** [comment]
Done for `alchemy`.

The [instructions](https://zenodo.org/account/settings/github/) aren't clear if this will create DOIs for existing releases. Will it only work with new ones?

**Comment by bas-rustenburg** [comment]
New ones only I believe.

**Comment by jchodera** [comment]
Well, that blows.

**Comment by bas-rustenburg** [comment]
You can still upload the old ones manually, it's not that much work.

**Comment by jchodera** [comment]
Ah, OK!

What other repos should we turn this on for?

**Comment by bas-rustenburg** [comment]
I'd suggest yank, not sure if others would be helpful at this point. Are there any other repos that would potentially be used in (soon to be) published work?

**Comment by bas-rustenburg** [comment]
Openmoltools maybe?

**Comment by jchodera** [comment]
OK, turned on a bunch.

**Comment by bas-rustenburg** [comment]
Closing this since we enabled it.
