### ISSUE TITLE
Merge alchemy and init?

### ISSUE THREAD

**Issue by bas-rustenburg** [choderalab/alchemy#37]
Is there a specific reason why there is both an `alchemy.py` and `__init__.py`? 

`__init__.py` just contains `from .alchemy import *` , so `alchemy.py` seems rather redundant.

**Comment by andrrizzi** [comment]
With Python 3 I think few things have changed, but if I remember correctly, having an `__init__.py` file is necessary in Python 2 to make it recognize a package. Didn't verify though, so I could be wrong.

**Comment by bas-rustenburg** [comment]
Yes, in python 3 as well. But at least structure wise, `alchemy.py` is redundant if all of its contents are imported into `__init__.py` already. Why not merge them into `__init__.py`?

**Comment by jchodera** [comment]
`alchemy.py` contains all of the actual classes!  I've never seen an `__init__.py` more than a few lines long.

**Comment by andrrizzi** [comment]
Sorry I misunderstood!

They are both equivalent solutions, so I guess it's just an organizational thing. If I was to explore a package that somebody else wrote on GitHub and found only an `__init__.py` file in it, my first thought would be that the package is empty. Probably more important, if we'll add new stuff and decide to separate into files in the future, we won't have to export everything from `__init__.py` again and ruin the file commit history.

**Comment by bas-rustenburg** [comment]
> Probably more important, if we'll add new stuff and decide to separate into files in the future, we won't have to export everything from **init**.py again and ruin the file commit history.

Good point, thanks! I was mostly wondering why the package structure was chosen like this since there is only the one `alchemy` module. It felt odd to me to use a package with an `__init__.py` if there is only one python module, and that gets imported into the `__init__.py` to avoid things like `from alchemy.alchemy import`.  

I think the less obscure / better alternative for single module packages would be not using a `alchemy` package directory and `__init__.py` file at all. Just leaving `alchemy.py` in the main directory, with the tests there as well. Then again, as you mentioned if you then end up adding more to the package later (not sure what the plans are) you'd revert to the old structure anyways. 

Mostly a matter of taste (feel free to close this) and I was curious about other opinions. It's helpful to think about the best module/package structures, since we're working on quite a variety in the lab these days.

**Comment by andrrizzi** [comment]
> It's helpful to think about the best module/package structures, since we're working on quite a variety in the lab these days.

Agreed!

Personally, I would keep the current structure. I agree that having `alchemy.py` in the main folder would make more sense given the current state, but from the user perspective all these solutions are identical because they still boil down to `from alchemy import AlchemicalFactory`; developers are used to this way of structuring the code (even if here it is an overkill) so they don't have problems in understanding where is what; and this is a slightly more extensible structure.

**Comment by bas-rustenburg** [comment]
Makes sense. Thanks for the feedback!
