### ISSUE TITLE
Unpin conda-build from 2.0.1 to fix travis

### ISSUE THREAD

**Issue by jchodera** [choderalab/alchemy#64]
Currently, [`devtools/travis-ci/install.sh` pins `conda-build==2.0.1`](https://github.com/choderalab/alchemy/blob/master/devtools/travis-ci/install.sh#L15), which [causes travis to fail](https://travis-ci.org/choderalab/alchemy/jobs/193469452#L489-L505).

@Lnaden : Can you create a PR to un-pin?

**Comment by Lnaden** [comment]
Yes, give me a bit to finish the debug run setup and I'll get to this one.

**Comment by Lnaden** [comment]
Fixed by #65
